# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x06\n\x04Null\"Q\n\x04Task\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\t\x12\x14\n\x0cis_completed\x18\x04 \x01(\x08\"=\n\x0eResponse_added\x12\x1c\n\x14\x64\x61ys_before_deadline\x18\x01 \x01(\r\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x02 \x01(\x08\"\'\n\x12Response_completed\x12\x11\n\tcompleted\x18\x01 \x01(\x08\x32]\n\x0cProcessTasks\x12#\n\x07\x41\x64\x64Task\x12\x05.Task\x1a\x0f.Response_added\"\x00\x12(\n\x08\x43omplete\x12\x05.Task\x1a\x13.Response_completed\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=16
  _NULL._serialized_end=22
  _TASK._serialized_start=24
  _TASK._serialized_end=105
  _RESPONSE_ADDED._serialized_start=107
  _RESPONSE_ADDED._serialized_end=168
  _RESPONSE_COMPLETED._serialized_start=170
  _RESPONSE_COMPLETED._serialized_end=209
  _PROCESSTASKS._serialized_start=211
  _PROCESSTASKS._serialized_end=304
# @@protoc_insertion_point(module_scope)
